language: node_js
node_js:
  - 18

services:
  - xvfb

cache:
  directories:
    - ~/.npm

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - npm install -g npm@latest

install:
  - npm install

script:
  - npm run test:unit
  - npm run test:e2e
